### ISSUE TITLE
🔴 Tasks TODO

### ISSUE THREAD

**Issue by aayu5hgit** [aayu5hgit/histograde#13]
- [ ] >95% accuracy on each feature
- [ ] Record algorithm for each feature
- [ ] Different DS for each features
- [ ] Integration (it will lower the accuracy, so the main thing is to fine tune as a whole) (Markow's chain if in ML, adaptive weights if in DL)
- [ ] Can we prioritize features to improve the time complexity?
- [ ] Study about features from research papers
- [ ] Trial and error methods (combine methods to improve)
